### ISSUE TITLE
Cannot read property 'codePointAt' of undefined

### ISSUE THREAD

**Issue by svoop** [yonchu/charcode-display#2]
Since Atom 1.20, the following error occurs sometimes when switching tabs:

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [charcode-display](https://github.com/yonchu/charcode-display) package 0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'codePointAt' of undefined

```
At /Users/sschwyn/.atom/packages/charcode-display/lib/charcode-display-view.coffee:53

TypeError: Cannot read property 'codePointAt' of undefined
    at HTMLDivElement.CharcodeDisplayView.updateCharcode (/packages/charcode-display/lib/charcode-display-view.coffee:53:42)
    at HTMLDivElement.CharcodeDisplayView.subscribeToActiveTextEditor (/packages/charcode-display/lib/charcode-display-view.coffee:35:6)
    at /packages/charcode-display/lib/charcode-display-view.coffee:22:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:339:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:492:27)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:715:25)
```

### Commands

```
     -4:08.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -3:00.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-html-preview 0.2.2 
busy-signal 1.4.3 
charcode-display 0.2.1 
color-picker 2.2.5 
dash 1.7.1 
editorconfig 2.2.2 
file-icons 2.1.12 
flex-tool-bar 0.12.0 
git-blame 1.3.1 
git-time-machine 1.5.9 
gusto-theme 0.1.0 
hex 0.6.2 
highlight-bad-chars 1.0.7 
intentions 1.1.5 
language-diff 0.7.0 
language-slim 0.6.0 
linter 2.2.0 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
merge-conflicts 1.4.5 
open-terminal-here 2.3.1 
pigments 0.40.2 
rails-transporter 1.7.1 
remote-atom 1.3.11 
rest-client 1.3.1 
sort-lines 0.15.0 
split-diff 1.5.1 
stacktrace 0.0.2 
symbols-tree-view 0.14.0 
tabs-to-spaces 1.0.3 
todo-show 2.0.0 
tool-bar 1.1.0 
tree-view-panes 0.3.7 
```

**Comment by svoop** [comment]
Steps to reproduce:

1. Open a directory containing text files with `atom .` or so.
2. In Atom, click on some of the text files in the project pane in order to open them as tabs.
3. Outside Atom, delete one of the text files clicked in the previous step.
4. In Atom. switch tabs. When you switch from the tab of an existing file to a no longer existing file, the error occurs.
